"""AI drafting workflow: generate -> human edits -> approve (plan §18).

Every AI draft starts as status='ai_suggestion'. Only explicit human actions
can move it to 'human_edited' or 'approved' (Rule 5).
"""
import re

from sqlalchemy.orm import Session

from app.core.config import settings
from app.core.exceptions import AppError, NotFoundError
from app.engines.content import drafting
from app.modules.article_planner.repository import ArticlePlannerRepository
from app.modules.content.repository import DraftsRepository
from app.modules.settings.service import SettingsService


class ContentService:
    def __init__(self, db: Session):
        self.db = db
        self.repo = DraftsRepository(db)
        self.plans = ArticlePlannerRepository(db)

    async def generate_draft(self, plan_id: int, provider: str | None = None) -> dict:
        plan = self.plans.get(plan_id)
        if plan is None:
            raise NotFoundError("plan.not_found", f"Article plan {plan_id} does not exist")
        if plan["status"] not in ("brief_ready", "drafting"):
            raise AppError(
                "plan.not_ready",
                f"Plan must be 'brief_ready' before drafting (current: {plan['status']})",
            )
        credentials = SettingsService(self.db).resolve_credentials(provider)
        result = await drafting.draft(plan, credentials["provider"], credentials["api_key"], credentials["model"])

        version = self.repo.next_version(plan_id)
        content_path = self._write_file(plan, version, result["content"])
        draft_id = self.repo.create(
            plan_id, version, result["content"], content_path, result["provider"], result["model"]
        )
        self.plans.update(plan_id, {"status": "drafting"})
        draft = self.repo.get(draft_id)
        draft["note"] = "This is an AI suggestion. Review and edit before approval."
        return draft

    @staticmethod
    def _write_file(plan: dict, version: int, content: str) -> str:
        content_dir = settings.data_dir / "content"
        content_dir.mkdir(parents=True, exist_ok=True)
        slug = re.sub(r"[^a-z0-9]+", "-", plan["title"].lower()).strip("-")[:60] or f"plan-{plan['id']}"
        path = content_dir / f"{plan['id']}-{slug}-v{version}.md"
        header = (
            f"<!-- AI SUGGESTION — generated by {plan['id']}. Not verified. Human approval required. -->\n\n"
        )
        path.write_text(header + content, encoding="utf-8")
        return str(path)

    def get_draft(self, draft_id: int) -> dict:
        draft = self.repo.get(draft_id)
        if draft is None:
            raise NotFoundError("draft.not_found", f"Draft {draft_id} does not exist")
        return draft

    def list_drafts(self, plan_id: int) -> list[dict]:
        return self.repo.list_for_plan(plan_id)

    def list_all_drafts(self, status: str | None = None) -> list[dict]:
        if status and status not in ("ai_suggestion", "human_edited", "approved"):
            raise AppError("draft.invalid_status_filter", f"Unknown draft status: {status}")
        return self.repo.list_all(status)

    def edit_draft(self, draft_id: int, content: str) -> dict:
        draft = self.get_draft(draft_id)
        self.repo.update(draft_id, content, "human_edited")
        return self.repo.get(draft_id)

    def approve_draft(self, draft_id: int) -> dict:
        draft = self.get_draft(draft_id)
        if "[VERIFY:" in draft["content"]:
            raise AppError(
                "draft.unverified_facts",
                "Draft still contains [VERIFY: ...] placeholders — resolve them before approving.",
            )
        self.repo.update(draft_id, draft["content"], "approved")
        return self.repo.get(draft_id)
